module.exports={
    education:[
        {id:0,name:'其他',status:0},
        {id:1,name:'专科',status:0},
        {id:10,name:'本科',status:1},
        {id:20,name:'硕士',status:0},
        {id:30,name:'博士',status:0},
        {id:40,name:'博士后',status:0},
        {id:50,name:'其他',status:0}
    ],
    turnover:[
        {id:0,name:'其他',status:0},
        {id:1,name:'1000万元以下',status:0},
        {id:10,name:'1000万元-5000万元',status:1},
        {id:20,name:'5000万元-1亿元',status:0},
        {id:30,name:'1亿元-10亿元',status:0},
        {id:40,name:'10亿元以上',status:0}
    ],
    lnasset:[
        {id:0,name:'其他',status:0},
        {id:1,name:'20人以下',status:0},
        {id:10,name:'20-100人',status:0},
        {id:20,name:'100-500人',status:1},
        {id:30,name:'500-1000人',status:0},
        {id:40,name:'1000-5000人',status:0},
        {id:50,name:'5000-10000人',status:0},
        {id:50,name:'10000人以上',status:0}
    ],
    trade:[
        {id:0,name:'其他',status:0},
        {id:1,name:'金融服务',status:1},
        {id:10,name:'咨询及信息服务',status:0},
        {id:20,name:'能源及环保',status:0},
        {id:30,name:'机械重工',status:0},
        {id:40,name:'消费品制造',status:0},
        {id:50,name:'计算机、互联网、电信',status:0},
        {id:60,name:'房地产及装饰',status:0},
        {id:70,name:'交通、运输及物流',status:0},
        {id:80,name:'服务行业',status:0},
        {id:90,name:'非盈利组织',status:0},
        {id:100,name:'政府机构',status:0},
        {id:110,name:'批发、零售、贸易',status:0},
        {id:120,name:'医疗、医药、保健、生物科技',status:0},
        {id:130,name:'媒体、广告、公关、文化',status:0},
        {id:140,name:'公共服务',status:0},
        {id:150,name:'教育、科研、培训',status:0},
        {id:160,name:'航空航天',status:0},
        {id:170,name:'农林牧渔',status:0},
        {id:180,name:'建筑业',status:0},
        {id:190,name:'采矿业',status:0},
        {id:200,name:'水利、环境和公共设施管理业',status:0},
        {id:210,name:'公共管理与社会组织',status:0},
        {id:220,name:'国际组织',status:0},
        {id:230,name:'科学研究、技术服务和地质勘查业',status:0},
        {id:240,name:'其他行业',status:0}
    ],
    level:[
        {id:0,name:'无',status:0},
        {id:1,name:'格局高管',status:1},
        {id:2,name:'教学中心',status:0},
        {id:3,name:'品牌宣传',status:0},
        {id:4,name:'综合办公室',status:0},
        {id:5,name:'新媒体中心',status:0},
        {id:6,name:'财务',status:0},
        {id:7,name:'工程',status:0},
        {id:8,name:'视觉传达中心',status:0},
        {id:9,name:'分院管理部',status:0},
        {id:10,name:'深圳办公室',status:0},
        {id:11,name:'全员培训中心',status:0},
    ],
    homeType:[
        {id:1,name:'课程班',status:0},
        {id:2,name:'活动',status:0},
        {id:3,name:'专辑',status:0},
        {id:4,name:'讲师',status:0},
        {id:5,name:'分院',status:0},
        {id:6,name:'广告',status:0},
        {id:7,name:'精彩视频',status:0},
        {id:8,name:'国际化',status:0},
        {id:9,name:'新专辑',status:0},
    ],
    informType:[
        {id:1,name:'上课提醒',pics:'http://files.gejubusiness.com/public/sktx.png'},
        {id:2,name:'课后评价',pics:'http://files.gejubusiness.com/public/khpj.png'},
        {id:3,name:'课程信息变更',pics:'http://files.gejubusiness.com/public/kcxxbg.png'},
        {id:4,name:'课程预告',pics:'http://files.gejubusiness.com/public/kcyg.png'},
        {id:5,name:'学员提问',pics:'http://files.gejubusiness.com/public/xytw.png'},
        {id:6,name:'公告',pics:'http://files.gejubusiness.com/public/gonggao.png'},
    ],
    branch:[
        {id:1,name:'院长',status:0},
        {id:2,name:'教务',status:0},
        {id:3,name:'班主任',status:0},
        {id:4,name:'班级助理',status:0},
        {id:5,name:'招生',status:0},
    ],
    city:[
        { name: "北京", cities: ["北京"] },
        { name: "天津", cities: ["天津"] },
        { name: "河北", cities: ["石家庄", "秦皇岛", "廊坊", "保定", "邯郸", "唐山", "邢台", "衡水", "张家口", "承德", "沧州", "衡水"] },
        { name: "山西", cities: ["太原", "大同", "长治", "晋中", "阳泉", "朔州", "运城", "临汾"] },
        { name: "内蒙古", cities: ["呼和浩特", "赤峰", "通辽", "锡林郭勒", "兴安"] },
        { name: "辽宁", cities: ["大连", "沈阳", "鞍山", "抚顺", "营口", "锦州", "丹东", "朝阳", "辽阳", "阜新", "铁岭", "盘锦", "本溪", "葫芦岛"] },
        { name: "吉林", cities: ["长春", "吉林", "四平", "辽源", "通化", "延吉", "白城", "辽源", "松原", "临江", "珲春"] },
        { name: "黑龙江", cities: ["哈尔滨", "齐齐哈尔", "大庆", "牡丹江", "鹤岗", "佳木斯", "绥化"] },
        { name: "上海", cities: ["上海"] },
        { name: "江苏", cities: ["南京", "苏州", "无锡", "常州", "扬州", "徐州", "南通", "镇江", "泰州", "淮安", "连云港", "宿迁", "盐城", "淮阴", "沐阳", "张家港"] },
        { name: "浙江", cities: ["杭州", "金华", "宁波", "温州", "嘉兴", "绍兴", "丽水", "湖州", "台州", "舟山", "衢州"] },
        { name: "安徽", cities: ["合肥", "马鞍山", "蚌埠", "黄山", "芜湖", "淮南", "铜陵", "阜阳", "宣城", "安庆"] },
        { name: "福建", cities: ["福州", "厦门", "泉州", "漳州", "南平", "龙岩", "莆田", "三明", "宁德"] },
        { name: "江西", cities: ["南昌", "景德镇", "上饶", "萍乡", "九江", "吉安", "宜春", "鹰潭", "新余", "赣州"] },
        { name: "山东", cities: ["青岛", "济南", "淄博", "烟台", "泰安", "临沂", "日照", "德州", "威海", "东营", "荷泽", "济宁", "潍坊", "枣庄", "聊城"] },
        { name: "河南", cities: ["郑州", "洛阳", "开封", "平顶山", "濮阳", "安阳", "许昌", "南阳", "信阳", "周口", "新乡", "焦作", "三门峡", "商丘"] },
        { name: "湖北", cities: ["武汉", "襄樊", "孝感", "十堰", "荆州", "黄石", "宜昌", "黄冈", "恩施", "鄂州", "江汉", "随枣", "荆沙", "咸宁"] },
        { name: "湖南", cities: ["长沙", "湘潭", "岳阳", "株洲", "怀化", "永州", "益阳", "张家界", "常德", "衡阳", "湘西", "邵阳", "娄底", "郴州"] },
        { name: "广东", cities: ["广州", "深圳", "东莞", "佛山", "珠海", "汕头", "韶关", "江门", "梅州", "揭阳", "中山", "河源", "惠州", "茂名", "湛江", "阳江", "潮州", "云浮", "汕尾", "潮阳", "肇庆", "顺德", "清远"] },
        { name: "广西", cities: ["南宁", "桂林", "柳州", "梧州", "来宾", "贵港", "玉林", "贺州"] },
        { name: "海南", cities: ["海口", "三亚"] },
        { name: "重庆", cities: ["重庆"] },
        { name: "四川", cities: ["成都", "达州", "南充", "乐山", "绵阳", "德阳", "内江", "遂宁", "宜宾", "巴中", "自贡", "康定", "攀枝花"] },
        { name: "贵州", cities: ["贵阳", "遵义", "安顺", "黔西南", "都匀"] },
        { name: "云南", cities: ["昆明", "丽江", "昭通", "玉溪", "临沧", "文山", "红河", "楚雄", "大理"] },
        { name: "西藏", cities: ["拉萨", "林芝", "日喀则", "昌都"] },
        { name: "陕西", cities: ["西安", "咸阳", "延安", "汉中", "榆林", "商南", "略阳", "宜君", "麟游", "白河"] },
        { name: "甘肃", cities: ["兰州", "金昌", "天水", "武威", "张掖", "平凉", "酒泉"] },
        { name: "青海", cities: ["黄南", "海南", "西宁", "海东", "海西", "海北", "果洛", "玉树"] },
        { name: "宁夏", cities: ["银川", "吴忠"] },
        { name: "新疆", cities: ["乌鲁木齐", "哈密", "喀什", "巴音郭楞", "昌吉", "伊犁", "阿勒泰", "克拉玛依", "博尔塔拉"] },
        { name: "台湾", cities: ["台湾"] },
        { name: "香港特别行政区", cities: ["香港特别行政区"] },
        { name: "澳门特别行政区", cities: ["澳门特别行政区"] }
    ],
    activityType:[
        {name:'走进名企',key:'cc6584e45fa26ce4'},
        {name:'金融投资会论坛',key:'bba6147df8e5672c'},
        {name:'学员联谊',key:'5ca3416f163e4977'},
        {name:'顶层设计',key:'bf2ce57f370e90fd'},
        {name:'硅谷创业节',key:'5212cbf664ff978b'},
        {name:'创新论坛',key:'2e91f7b6f2ea833c'},
        {name:'斯坦福精品课程',key:'370a74fe37b86c1a'},
        {name:'名企访问',key:'5fd885c3adc54265'},
        {name:'文化之旅',key:'99eb0d8389805978'},
        {name:'硅谷游记',key:'42aac317f04e1c73'},
        {name:'朋友圈',key:'ea1cdd9b56fb2a6c'},
    ],
}